import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/ThemeProvider";
import Container from "@/components/Container";
import Navbar from "@/app/Navbar";
import Footer from "@/app/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <main className="flex-grow sm:p-10 p-5">
            <Container>{children}</Container>
          </main>
          <Footer/>
        </div>
      </ThemeProvider>
      </body>
      </html>
  );
}
